# This file is autogenerated by gen-pydantic precommit
from __future__ import annotations

import re
import sys
from datetime import (
    date,
    datetime,
    time
)
from decimal import Decimal
from enum import Enum
from typing import (
    Any,
    ClassVar,
    Literal,
    Optional,
    Union
)

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SerializationInfo,
    SerializerFunctionWrapHandler,
    field_validator,
    model_serializer
)


metamodel_version = "None"
version = "1.0.0-alpha"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        serialize_by_alias = True,
        validate_by_name = True,
        validate_assignment = True,
        validate_default = True,
        extra = "forbid",
        arbitrary_types_allowed = True,
        use_enum_values = True,
        strict = False,
    )

    @model_serializer(mode='wrap', when_used='unless-none')
    def treat_empty_lists_as_none(
            self, handler: SerializerFunctionWrapHandler,
            info: SerializationInfo) -> dict[str, Any]:
        if info.exclude_none:
            _instance = self.model_copy()
            for field, field_info in type(_instance).model_fields.items():
                if getattr(_instance, field) == [] and not(
                        field_info.is_required()):
                    setattr(_instance, field, None)
        else:
            _instance = self
        return handler(_instance, info)



class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key:str):
        return getattr(self.root, key)

    def __getitem__(self, key:str):
        return self.root[key]

    def __setitem__(self, key:str, value):
        self.root[key] = value

    def __contains__(self, key:str) -> bool:
        return key in self.root


linkml_meta = None

class PrimerSchemeDevelopmentStatus(str, Enum):
    """
    Status of this amplicon primer scheme
    """
    DRAFT = "DRAFT"
    """
    A primer scheme that has been designed but requires further testing and validation.
    """
    TESTED = "TESTED"
    """
    A primer scheme that has been translated into a physical primer mixture that has been evaluated on samples.
    """
    VALIDATED = "VALIDATED"
    """
    A primer scheme that has been translated into a physical primer mixture and determined to work as expected on a range of samples.
    """
    DEPRECATED = "DEPRECATED"
    """
    A primer scheme that is no longer recommended for use because it is outdated or has been replaced by a better alternative.
    """
    WITHDRAWN = "WITHDRAWN"
    """
    A primer scheme that has been removed or retracted so that it is no longer available.
    """


class PrimerSchemeLicense(str, Enum):
    """
    License under which the primer scheme is distributed
    """
    CC0_1FULL_STOP0 = "CC0-1.0"
    CC_BY_4FULL_STOP0 = "CC-BY-4.0"
    CC_BY_SA_4FULL_STOP0 = "CC-BY-SA-4.0"
    CC_BY_NC_4FULL_STOP0 = "CC-BY-NC-4.0"
    CC_BY_NC_SA_4FULL_STOP0 = "CC-BY-NC-SA-4.0"
    CC_BY_ND_4FULL_STOP0 = "CC-BY-ND-4.0"
    CC_BY_NC_ND_4FULL_STOP0 = "CC-BY-NC-ND-4.0"


class PrimerSchemeApplication(str, Enum):
    """
    The application the primer scheme was intended for.
    """
    CLINICAL = "CLINICAL"
    """
    An entity used in a clinical setting.
    """
    WASTEWATER = "WASTEWATER"
    """
    An entity used for studying and/or testing wastewater.
    """


class PrimerSchemeScope(str, Enum):
    """
    The range of targets the primer scheme is intented for.
    """
    WHOLE_GENOME = "WHOLE-GENOME"
    """
    A primer scheme designed to target a whole genome via a series of tiling amplicons.
    """
    PANEL = "PANEL"
    """
    A primer scheme designed to target multiple specific genes and mutations.
    """
    QPCR = "QPCR"
    """
    A primer scheme designed to target a single genetic region as part of a Quantitative Polymerase Chain Reaction (qPCR) assay.
    """



class PrimerScheme(ConfiguredBaseModel):
    """
    A tiled amplicon PCR primer scheme definition
    """
    schema_version: str = Field(default=..., description="""The version of the schema used to create this scheme definition""")
    primer_scheme_name: str = Field(default=..., description="""The name of the primer scheme used in an assay.""")
    amplicon_size: int = Field(default=..., description="""The length of the amplicon generated by PCR amplification.""", ge=1)
    primer_scheme_version: str = Field(default=..., description="""The version of the primer scheme.""")
    primer_scheme_identifier: Optional[str] = Field(default=None, description="""The unique identifier combining the name, amplicon_size and version deliminated by \"/\"""")
    primer_scheme_contributor: list[PrimerSchemeContributor] = Field(default=..., description="""Individuals, organisations, or institutions that have contributed to the development""", min_length=1)
    primer_scheme_target_organism: list[PrimerSchemeTargetOrganism] = Field(default=..., description="""The organism against which this primer scheme is targeted.""", min_length=1)
    primer_scheme_identifier_alias: Optional[list[str]] = Field(default=[], description="""An alternative name for a primer scheme.""")
    primer_scheme_license: Optional[PrimerSchemeLicense] = Field(default='CC-BY-SA-4.0', description="""The license under which the primer scheme is distributed""")
    primer_scheme_development_status: PrimerSchemeDevelopmentStatus = Field(default=..., description="""The status of the of the primer scheme in its development cycle.""")
    primer_scheme_application: Optional[PrimerSchemeApplication] = Field(default=None, description="""The application the primer scheme was intended for.""")
    primer_scheme_scope: Optional[PrimerSchemeScope] = Field(default=None, description="""The range of targets the primer scheme is intented for.""")
    primer_scheme_derived_from: Optional[str] = Field(default=None, description="""The original primer scheme from which the present scheme was derived.""")
    citation: Optional[list[str]] = Field(default=[], description="""A textual entity intended to identify a particular publication.""")
    primer_scheme_details: Optional[list[str]] = Field(default=[], description="""Any additional information about a primer scheme outside of the primer scheme specification.""")
    primer_scheme_vendor: Optional[list[PrimerSchemeVendor]] = Field(default=[], description="""Vendors where one can purchase the primers described in the amplicon scheme or a kit containing these primers""")
    primer_scheme_generator: Optional[PrimerSchemeGenerator] = Field(default=None, description="""The algorithm (if any) used to generate this primer scheme""")
    primer_scheme_checksums: Optional[PrimerSchemeChecksums] = Field(default=None, description="""SHA256 checksums for scheme files""")
    primer_scheme_creation_date: Optional[date] = Field(default=None, description="""The date the primer scheme was created.""")
    primer_scheme_submission_date: Optional[date] = Field(default=None, description="""The date the primer scheme was submitted to a repository.""")

    @field_validator('primer_scheme_name')
    def pattern_primer_scheme_name(cls, v):
        pattern=re.compile(r"^(?!\.{1,2}$)[\da-z0-9_.-]+$")
        if isinstance(v, list):
            for element in v:
                if isinstance(element, str) and not pattern.match(element):
                    err_msg = f"Invalid primer_scheme_name format: {element}"
                    raise ValueError(err_msg)
        elif isinstance(v, str) and not pattern.match(v):
            err_msg = f"Invalid primer_scheme_name format: {v}"
            raise ValueError(err_msg)
        return v

    @field_validator('primer_scheme_version')
    def pattern_primer_scheme_version(cls, v):
        pattern=re.compile(r"^v\d+\.\d+\.\d+(-[a-z0-9]+)?$")
        if isinstance(v, list):
            for element in v:
                if isinstance(element, str) and not pattern.match(element):
                    err_msg = f"Invalid primer_scheme_version format: {element}"
                    raise ValueError(err_msg)
        elif isinstance(v, str) and not pattern.match(v):
            err_msg = f"Invalid primer_scheme_version format: {v}"
            raise ValueError(err_msg)
        return v


class PrimerSchemeVendor(ConfiguredBaseModel):
    """
    Vendor of the primers described in the amplicon scheme or a kit containing these primers
    """
    primer_scheme_vendor_name: str = Field(default=..., description="""The name of the vendor supplying a commercialized product based on the primer scheme.""")
    primer_scheme_vendor_url: Optional[str] = Field(default=None, description="""The URL of the primer scheme vendor's website.""")
    primer_scheme_vendor_kit_name: Optional[str] = Field(default=None, description="""The name of the primer kit implementing the primer scheme.""")


class PrimerSchemeContributor(ConfiguredBaseModel):
    """
    Person or organisation who contributed to primer scheme development
    """
    primer_scheme_contributor_name: str = Field(default=..., description="""The name of the individual, organisation, and/or institution that contributed to the development of the primer scheme.""")
    primer_scheme_contributor_orcid: Optional[str] = Field(default=None, description="""The Open Researcher and Contributor ID (ORCID) of the individual that contributed to the development of the primer scheme.""")
    primer_scheme_contributor_email: Optional[str] = Field(default=None, description="""The email address of the individual that contributed to the development of the primer scheme.""")

    @field_validator('primer_scheme_contributor_email')
    def pattern_primer_scheme_contributor_email(cls, v):
        pattern=re.compile(r"^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$")
        if isinstance(v, list):
            for element in v:
                if isinstance(element, str) and not pattern.match(element):
                    err_msg = f"Invalid primer_scheme_contributor_email format: {element}"
                    raise ValueError(err_msg)
        elif isinstance(v, str) and not pattern.match(v):
            err_msg = f"Invalid primer_scheme_contributor_email format: {v}"
            raise ValueError(err_msg)
        return v


class PrimerSchemeGenerator(ConfiguredBaseModel):
    """
    Algorithm used to generate the primer scheme
    """
    primer_scheme_generator_name: str = Field(default=..., description="""The name of the method used to develop the primer scheme.""")
    primer_scheme_generator_version: Optional[str] = Field(default=None, description="""The version of the method used to develop the primer scheme.""")


class PrimerSchemeChecksums(ConfiguredBaseModel):
    """
    SHA256 checksums for scheme files
    """
    primer_scheme_sha256: Optional[str] = Field(default=None, description="""A small-sized block of data (checksum) derived from the primer scheme BED file for the purpose of detecting differences across schemes.""")
    reference_sequence_sha256: Optional[str] = Field(default=None, description="""A small-sized block of data (checksum) derived from the reference sequence for the purpose of detecting differences across sequences.""")

    @field_validator('primer_scheme_sha256')
    def pattern_primer_scheme_sha256(cls, v):
        pattern=re.compile(r"^[a-fA-F0-9]{64}$")
        if isinstance(v, list):
            for element in v:
                if isinstance(element, str) and not pattern.match(element):
                    err_msg = f"Invalid primer_scheme_sha256 format: {element}"
                    raise ValueError(err_msg)
        elif isinstance(v, str) and not pattern.match(v):
            err_msg = f"Invalid primer_scheme_sha256 format: {v}"
            raise ValueError(err_msg)
        return v

    @field_validator('reference_sequence_sha256')
    def pattern_reference_sequence_sha256(cls, v):
        pattern=re.compile(r"^[a-fA-F0-9]{64}$")
        if isinstance(v, list):
            for element in v:
                if isinstance(element, str) and not pattern.match(element):
                    err_msg = f"Invalid reference_sequence_sha256 format: {element}"
                    raise ValueError(err_msg)
        elif isinstance(v, str) and not pattern.match(v):
            err_msg = f"Invalid reference_sequence_sha256 format: {v}"
            raise ValueError(err_msg)
        return v


class PrimerSchemeTargetOrganism(ConfiguredBaseModel):
    """
    The organisms targeted by this primer scheme
    """
    primer_scheme_target_organism_name: Optional[str] = Field(default=None, description="""The name of the taxon or taxa that the primers of the scheme were designed to target.""")
    primer_scheme_target_organism_ncbi_taxon_id: Optional[str] = Field(default=None, description="""The NCBI taxon ID of the taxon or taxa that the primers of the scheme were designed to target.""")
    primer_scheme_target_organism_details: Optional[str] = Field(default=None, description="""Any additional information about a primer scheme target.""")


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
PrimerScheme.model_rebuild()
PrimerSchemeVendor.model_rebuild()
PrimerSchemeContributor.model_rebuild()
PrimerSchemeGenerator.model_rebuild()
PrimerSchemeChecksums.model_rebuild()
PrimerSchemeTargetOrganism.model_rebuild()
